---
#circleci configuration file
version: 2.1

orbs:
  aws-s3: circleci/aws-s3@4.0
  
jobs:
  build:
    docker:
      - image: cimg/aws:2023.09
    steps:
      - checkout
      - run: aws --version
        